version: '3'
services:
  web:
    image: bangomc/crudloopback:1
    ports:
      - "3000:3000"
  mysql:
    image: mysql:5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD: "masterkey"
      - MYSQL_DATABASE: "listadb"
      - MYSQL_USER: "dbuser"
